### ISSUE TITLE
Some style error at Safari

### ISSUE THREAD

**Issue by bolechen** [stephenlake/nova-snowball#1]
Nova Version: 2.0.1
Safari Version: Version 12.1 (14607.1.40.1.4)

When i use to a fresh installed Nova app, in my Safari brower the top looks some little error.
But at Chrome is seems nothing wrong.

Here is the screenshot.

<img width="1531" alt="Screen Shot 2019-04-27 at 21 32 56" src="https://user-images.githubusercontent.com/195015/56850385-80b3e580-6934-11e9-992e-22d593b5995b.png">

<img width="1531" alt="Screen Shot 2019-04-27 at 21 32 59" src="https://user-images.githubusercontent.com/195015/56856360-c780fa00-698b-11e9-850f-e7f839bd6062.png">

btw. Thanks for the good theme. <B

**Comment by stephenlake** [comment]
This bug actually lies within the dependency [nova-fixed-bars](https://github.com/stephenlake/nova-fixed-bars) on [issue-2](https://github.com/stephenlake/nova-fixed-bars/issues/2).

The problem amongst a struggle for time to work on open source stuff, is testing on Safari since I'm a linux user and I'd really like to avoid installing WINE for this... If anyone is willing to help out an submit a PR, I'll buy you a beer :beer:

**Comment by stephenlake** [comment]
@bolechen Does this still happen using 1.0.2?

**Comment by stephenlake** [comment]
Fixed javascript in [Nova Fixed Bars 1.0.6](https://github.com/stephenlake/nova-fixed-bars/releases/tag/v1.0.6). Please let me know if the issue persists.

**Comment by bolechen** [comment]
wow~ 1.0.6 worked for me, thx for your quick response.
